version: "3.9"
services: 
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
  postgres:
    image: 'postgres:latest'
    platform: linux/arm64
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grpcDB
      PGDATA: /var/lib/postgresql/data/culo/
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  blogs:
    build: ./blogs
    ports: 
      - 50051:50051
    depends_on: 
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grpcDB
      BLOG_URL: blogs:50051
    restart: always
  users:
    build: ./users
    ports: 
      - "50050:50050"
    depends_on: 
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grpcDB
    restart: always
  graphql-go:
    build: ./graphql-go
    ports:
      - "3001:3001"
    environment:
      USER_URL: users:50050
      BLOG_URL: blogs:50051
    restart: always
  graphql-node:
    build: ./graphql-node
    ports: 
      - "3002:3002"
    environment:
      USER_URL: users:50050
      BLOG_URL: blogs:50051
  rest-go:
    build: ./rest-go
    ports:
      - "3000:3000"
    environment:
      USER_URL: users:50050
      BLOG_URL: blogs:50051
  rest-node:
    build: ./rest-node
    ports:
      - "3003:3003"
    environment:
      USER_URL: users:50050
      BLOG_URL: blogs:50051

volumes: 
  data: