// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewBlog struct {
	UserID  int    `json:"userId"`
	Content string `json:"content"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
